CREATE TABLE `active_generation` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`chat_id` integer NOT NULL,
	`human_message_id` integer NOT NULL,
	`message_id` integer NOT NULL,
	`variant_id` integer NOT NULL,
	`human_participant_id` integer NOT NULL,
	`model_participant_id` integer NOT NULL,
	`captured_model_name` text NOT NULL,
	`started_at` text NOT NULL,
	`prompt_plan_json` text NOT NULL,
	`history_roles_json` text NOT NULL,
	`generation_settings_json` text NOT NULL,
	`connection_json` text NOT NULL,
	`provenance_namespace` text,
	`provenance_key` text,
	`provenance_value` text,
	FOREIGN KEY (`chat_id`) REFERENCES `chat`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`human_message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`variant_id`) REFERENCES `message_variant`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`human_participant_id`) REFERENCES `participant`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`model_participant_id`) REFERENCES `participant`(`id`) ON UPDATE no action ON DELETE no action
);
