CREATE TABLE `generation_replay` (
	`id` integer PRIMARY KEY NOT NULL,
	`chat_id` integer NOT NULL,
	`message_id` integer NOT NULL,
	`variant_id` integer NOT NULL,
	`human_participant_id` integer NOT NULL,
	`model_participant_id` integer NOT NULL,
	`captured_human_name` text NOT NULL,
	`captured_model_name` text NOT NULL,
	`started_at` text NOT NULL,
	`prompt_plan_json` text NOT NULL,
	`prompt_inspection_json` text NOT NULL,
	`history_roles_json` text NOT NULL,
	`generation_settings_json` text NOT NULL,
	`connection_json` text NOT NULL,
	`generation_intent_json` text NOT NULL,
	`checkpoint_content` text NOT NULL,
	`checkpoint_reasoning` text NOT NULL,
	`checkpoint_event_id` integer NOT NULL,
	`checkpointed_at` text,
	`terminal_status` text NOT NULL,
	`terminal_at` text NOT NULL,
	`expires_at` text NOT NULL,
	FOREIGN KEY (`chat_id`) REFERENCES `chat`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`variant_id`) REFERENCES `message_variant`(`id`) ON UPDATE no action ON DELETE cascade
);
